### PR TITLE
Implement doubleclick event

### PR DESCRIPTION
**Pull request by inlet**
Hi Sveinn Flóki,

First of all thanks for this wonderful lib, really useful! 
I've added double click support, please let me know what you think of it.

Cheers, Patrick
- Update `README.md`
- Add `mouse.doubleClick()`

### CODE REVIEW

**Comment by Loknar** [comment]
Hi Patrick Brouwer,

Thanks :smile:

I like your doubleClick function, I'll try it out when I have the time (this evening or tomorrow) and if I feel it functions properly I'll accept merging it and do a `1.1.0` release.

As for the keyboard functionality my view is that it's a different input device and would deserve to live as a separate module. I also have a mixed feeling about this hard coding approach, according to [this comment](http://stackoverflow.com/questions/1918841/how-to-convert-ascii-character-to-cgkeycode/14529841#comment28390740_14529841) it only works for the U.S. qwerty keyboard layout. The accepted answer above uses Carbon to fetch the keyboard layout, I know Carbon is dead and gone but as Cocoa is its successor it might hold similar functionality to fetch the keyboard layout (I'm only guessing here though).

Here is one attempt I know of making a keyboard module: https://github.com/ctwhome/node-mackeyboard, you could check it out and maybe contribute to it if you like.

**Comment by daanvanhasselt** [comment]
I agree that this module might not be the right place for the keyboard functionality but as we're using it in a project it seemed convenient enough to extend it for our needs. Anyway @inlet I suggest you do a separate pull request from a feature branch for the doubleclick functionality so @Loknar can merge that in and do a 1.1.0 release. I might fork https://github.com/ctwhome/node-mackeyboard and spend some time on supporting keyboard layouts etc.

**Comment by inlet** [comment]
Good one! @Loknar I'll create a new PR for only the double click.

**Comment by inlet** [comment]
@daanvanhasselt The keyboard support is now in a separate branch as well: https://github.com/inlet/node-macmouse/tree/experimental-keyboard-support.

**Pull request closed without merging**
